## Data Pre-Processing

In [11]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = np.random.randint(0, 100, (10, 2))

In [3]:
data

array([[32, 94],
       [16, 35],
       [ 0, 71],
       [36, 30],
       [23, 46],
       [48, 13],
       [66, 21],
       [58, 98],
       [49, 50],
       [14, 36]])

### Data Normalization

In [4]:
scaler_model = MinMaxScaler()

In [5]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [6]:
scaler_model.fit(data)

/home/einsteinekeine/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data) # it transform each element to between as 0 to 1

array([[0.48484848, 0.95294118],
       [0.24242424, 0.25882353],
       [0.        , 0.68235294],
       [0.54545455, 0.2       ],
       [0.34848485, 0.38823529],
       [0.72727273, 0.        ],
       [1.        , 0.09411765],
       [0.87878788, 1.        ],
       [0.74242424, 0.43529412],
       [0.21212121, 0.27058824]])

In [10]:
scaler_model.fit_transform(data) # it runs both process at once

/home/einsteinekeine/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.48484848, 0.95294118],
       [0.24242424, 0.25882353],
       [0.        , 0.68235294],
       [0.54545455, 0.2       ],
       [0.34848485, 0.38823529],
       [0.72727273, 0.        ],
       [1.        , 0.09411765],
       [0.87878788, 1.        ],
       [0.74242424, 0.43529412],
       [0.21212121, 0.27058824]])

* You should fit and transform the training data and just transform the test data. Because you can not expect how the test data looks like.

In [14]:
my_data = np.random.randint(0, 101, (50, 4))
my_data

array([[ 96,  27,  40,  67],
       [ 69,  78,   3,   1],
       [ 35,  67,  50,  18],
       [ 64,  34,  69,  59],
       [ 31,  60,  63,  25],
       [ 61,  95,  77,  91],
       [ 39,  31,  18,  34],
       [ 39,  79,  42,  30],
       [  9,  80,  16,  21],
       [ 43,  83,  23,   2],
       [ 77,  19,  46,  61],
       [ 83,  36,  95,  12],
       [ 59,  36,  26,   0],
       [ 88,  17,  31,  73],
       [ 62,  32,  75,  15],
       [ 38,  24,  37,  64],
       [ 14,  74,  42,  24],
       [ 45,  67,  80,   1],
       [ 93,  89,  27,  66],
       [  6,  48,  66,  12],
       [ 58,  92,  25,  78],
       [ 25,  77,  12,  43],
       [ 54,  11,  34,   8],
       [ 84,  30,   4,  36],
       [ 36,   4,  79,  28],
       [ 79,   7,  63,  31],
       [ 42,  45,  18,  66],
       [ 84,  47,   2,   3],
       [ 44,  73,  67,  26],
       [ 70,  24,   3,  80],
       [ 84,  31,  58,  80],
       [ 80,  54,  24,   2],
       [ 45,  84,   5,  18],
       [ 62,  54,  85,  63],
       [ 22,  

In [18]:
df = pd.DataFrame(data=my_data, columns=['f1', 'f2', 'f3', 'label'])

In [19]:
df

f1   f2  f3  label
0   96   27  40     67
1   69   78   3      1
2   35   67  50     18
3   64   34  69     59
4   31   60  63     25
5   61   95  77     91
6   39   31  18     34
7   39   79  42     30
8    9   80  16     21
9   43   83  23      2
10  77   19  46     61
11  83   36  95     12
12  59   36  26      0
13  88   17  31     73
14  62   32  75     15
15  38   24  37     64
16  14   74  42     24
17  45   67  80      1
18  93   89  27     66
19   6   48  66     12
20  58   92  25     78
21  25   77  12     43
22  54   11  34      8
23  84   30   4     36
24  36    4  79     28
25  79    7  63     31
26  42   45  18     66
27  84   47   2      3
28  44   73  67     26
29  70   24   3     80
30  84   31  58     80
31  80   54  24      2
32  45   84   5     18
33  62   54  85     63
34  22   80  11     51
35  63  100  71     58
36  31    1  86     95
37  14    4  14     42
38  90   61  92      5
39  97   24  23     53
40  65    6   7     96
41  72   85  18     21
42  27    7  90     80
43   1   11   6     63
44  17   40  40     55
45  57   11  95     79
46  51   48  83      9
47  10   52  43     49
48  15   75  57     98
49  38   72  61     97

### Train-Test Data Split

In [23]:
from sklearn.model_selection import train_test_split

In [20]:
x = df[['f1', 'f2', 'f3']]

In [22]:
y = df['label']

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [27]:
x_train.shape

(35, 3)

In [30]:
x_test.shape

(15, 3)